# Generated by Django 4.2.2 on 2023-07-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.RemoveField(
            model_name="prompt",
            name="prompt_category",
        ),
        migrations.RemoveField(
            model_name="prompt",
            name="prompt_note",
        ),
        migrations.AlterField(
            model_name="prompt",
            name="prompt_language",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="prompt",
            name="prompt_output",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="prompt",
            name="prompt_text",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="prompt",
            name="prompt_title",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
