# Generated by Django 4.2.2 on 2023-07-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "prompt",
            "0002_alter_category_options_remove_prompt_prompt_category_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="paragraph",
            name="paragraph_title",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="paragraph",
            name="paragraph_text",
            field=models.TextField(null=True),
        ),
    ]
