# Generated by Django 4.2.2 on 2023-07-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt", "0003_paragraph_paragraph_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="section_description",
            field=models.TextField(null=True),
        ),
    ]
