# Generated by Django 4.2.2 on 2023-07-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt", "0004_section_section_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="paragraph",
            name="paragraph_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="paragraph_images"
            ),
        ),
    ]
