# Generated by Django 4.2.2 on 2023-07-06 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prompt", "0005_paragraph_paragraph_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paragraph",
            name="paragraph_image",
        ),
    ]
