# Generated by Django 4.2.2 on 2023-07-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt", "0006_remove_paragraph_paragraph_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="prompt_level",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
