# Generated by Django 4.2.2 on 2023-07-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt", "0007_prompt_prompt_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="category_svg",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="category_information",
            field=models.TextField(null=True),
        ),
    ]
