# Generated by Django 4.2.2 on 2023-07-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt", "0008_category_category_svg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="prompt_category",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
