# Generated by Django 4.2.2 on 2023-07-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt", "0009_prompt_prompt_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="paragraphs",
            field=models.ManyToManyField(blank=True, to="prompt.paragraph"),
        ),
    ]
