# Generated by Django 4.2.2 on 2023-07-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt", "0012_alter_prompt_paragraphs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prompt",
            name="paragraphs",
        ),
        migrations.AddField(
            model_name="paragraph",
            name="prompts",
            field=models.ManyToManyField(blank=True, to="prompt.prompt"),
        ),
    ]
