# Generated by Django 4.2.2 on 2023-07-12 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("prompt", "0013_remove_prompt_paragraphs_paragraph_prompts"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subparagraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subparagraph_title", models.CharField(max_length=255, null=True)),
                ("subparagraph_text", models.TextField(null=True)),
                (
                    "paragraph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prompt.paragraph",
                    ),
                ),
                ("prompts", models.ManyToManyField(blank=True, to="prompt.prompt")),
            ],
        ),
    ]
