# Generated by Django 4.2.2 on 2023-07-12 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prompt", "0014_subparagraph"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subparagraph",
        ),
    ]
