# Generated by Django 4.2.2 on 2023-07-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt", "0016_subparagraph"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompt",
            name="prompt_title",
            field=models.CharField(max_length=45, null=True),
        ),
    ]
