# Generated by Django 4.2.2 on 2023-07-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt", "0017_alter_prompt_prompt_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subparagraph",
            name="subparagraph_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
