# Generated by Django 4.2.3 on 2023-08-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt", "0019_simplepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="prompt_emoji",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
