# Generated by Django 4.2.3 on 2023-08-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt", "0020_prompt_prompt_emoji"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompt",
            name="prompt_emoji",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
